# Generated by Django 5.0.6 on 2024-05-17 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='File')),
                ('type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('music', 'Music'), ('video', 'Video')], max_length=60, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Review')),
                ('rank', models.IntegerField(verbose_name='Rank')),
                ('customer_name', models.CharField(max_length=80, verbose_name='Customer Name')),
                ('customer_position', models.CharField(max_length=60, verbose_name='Customer Position')),
                ('customer_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media')),
            ],
            options={
                'verbose_name': 'Customer feedback',
                'verbose_name_plural': 'Customer feesbacks',
            },
        ),
        migrations.CreateModel(
            name='OurInstagramStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_link', models.URLField(verbose_name='Story link')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_stories', to='common.media')),
            ],
            options={
                'verbose_name': 'Our instagram story',
                'verbose_name_plural': 'Our instagram stories',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='common.country')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=120, verbose_name='Title')),
                ('home_subtitle', models.CharField(max_length=120, verbose_name='Subtitle')),
                ('home_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.media')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
