# Generated by Django 5.0.6 on 2024-05-17 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ImageField(upload_to='', verbose_name='Otp code')),
                ('type', models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset password')], max_length=60, verbose_name='Verification Type')),
                ('expires_in', models.DateTimeField(verbose_name='Expires_in')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Otp',
                'verbose_name_plural': 'Verification Otps',
            },
        ),
    ]
